name: Deploy Express Server

on:
  push:
    branches: [ main ] # or "master" if your default branch is that

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server # all commands run inside /server folder

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run build if applicable
      - name: Build project
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then
            npm run build
          else
            echo "No build script found, skipping build."
          fi

      # 5️⃣ Run tests (optional)
      - name: Run tests
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm test
          else
            echo "No test script found, skipping tests."
          fi

      # 6️⃣ Deploy (example: SSH to server)
      - name: Deploy to VPS
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/express-app
            git pull origin main
            cd server
            npm ci
            pm2 restart all
