name: 🚀 Deploy React Client to AWS CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy React Client to AWS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1                 # 🔧 change to your AWS region
      S3_BUCKET: your-s3-bucket-name         # 🔧 replace with your S3 bucket name
      CLOUDFRONT_DISTRIBUTION_ID: YOUR_ID    # 🔧 replace with your CloudFront distribution ID

    steps:
      - name: 🧭 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: 📦 Install dependencies
        working-directory: ./client
        run: npm ci

      - name: 🏗️ Build React App
        working-directory: ./client
        run: npm run build

      - name: ☁️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 📤 Sync build to S3
        run: |
          aws s3 sync client/build/ s3://${{ env.S3_BUCKET }} \
            --delete \
            --cache-control "public, max-age=31536000"

      - name: 🧹 Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: ✅ Deployment complete
        run: echo "🎉 React client successfully deployed to CloudFront!"
